BuyHouse/BuyHouse/Models/Home/PropertyViewModel.cs
namespace BuyHouse.Models.Home
{
    public class PropertyViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string ImageUrl { get; set; }

        public string City { get; set; }
    }
}

BuyHouse/BuyHouse/Models/Properties/AllPropertyModel.cs
namespace BuyHouse.Models.Properties
{
    using BuyHouse.Services.Properties.Models;
    using System.Collections.Generic;


    public class AllPropertyModel : PageViewModel
    {
        public int TotalProperties { get; set; }

        public string Transaction { get; set; }

        public string City { get; set; }

        public string Construction { get; set; }

        public IEnumerable<string> Constructions { get; set; }

        public IEnumerable<string> Cities { get; set; }

        public IEnumerable<string> Transactions { get; set; }

        public IEnumerable<PropertyServiceListModel> Properties { get; set; }
    }
}

BuyHouse/BuyHouse/Models/Properties/PropertyFormModel.cs
namespace BuyHouse.Models.Properties
{
    using BuyHouse.Services.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstant.Property;

    public class PropertyFormModel
    {
        [Range(AreaMinValue, AreaMaxValue)]
        public int Area { get; set; }

        [Required]
        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength)]
        public string Title { get; set; }

        [Range(YearMinValue, YearMaxValue)]
        public int Year { get; set; }

        public int? Floor { get; set; }

        public int? Floors { get; set; }

        public int? BedRoom { get; set; }

        public int? Bath { get; set; }

        [Range(PriceMinValue, PriceMaxValue)]
        public int Price { get; set; }

        [Required]
        [Url]
        [Display(Name = "Image URL")]
        public string ImageUrl { get; set; }

        [Required]
        [StringLength(DescriptionMaxLength, MinimumLength = DescriptionMinLength)]
        public string Description { get; set; }

        [Display(Name = "Category")]
        public int CategotyId { get; set; }

        [Required]
        [StringLength(CityNameMaxLength, MinimumLength = CityNameMinLength)]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [StringLength(ConstructionMaxLength, MinimumLength = ConstructionMinLength)]
        [Display(Name = "Construction")]
        public string Construction { get; set; }

        [Display(Name = "Agent")]
        public int? AgentId { get; set; }

        [Required]
        [StringLength(TypeOfTransactionMaxLength, MinimumLength = TypeOfTransactionMinLength)]
        [Display(Name = "Type of Transaction")]
        public string TypeOfTransaction { get; set; }

        public IEnumerable<PropertyCategoryServiceModel> Categories { get; set; }

    }
}

BuyHouse/BuyHouse/Areas/Admin/Controllers/PropertiesController.cs
namespace BuyHouse.Areas.Admin.Controllers
{
    using BuyHouse.Models.Properties;
    using BuyHouse.Services.Properties;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static AdminConstants;

    [Area(AreaName)]
    [Authorize(Roles = AdministratolRoleName)]
    public class PropertiesController : Controller
    {
        private const int propertiesPerPage = 5;

        private readonly IPropertyService service;

        public PropertiesController(IPropertyService service) 
        {
            this.service = service;
        }
        public IActionResult All([FromQuery] AllPropertyModel property) 
        {
            var queryProperties = this.service.All(
                property.Transaction,
                property.City,
                property.Construction,
                property.CurentPage,
                propertiesPerPage,
                publicOnly: false);

            var propertiesCity = this.service.AllCity();

            property.TotalProperties = queryProperties.TotalProperties;
            property.Cities = propertiesCity;
            property.Properties = queryProperties.Properties;

            return this.View(property);
        }

        public IActionResult Approve(int id) 
        {
            this.service.Approve(id);

            return RedirectToAction("All", "Properties");
        }
    }
}

BuyHouse/BuyHouse/Controllers/IssuesController.cs
namespace BuyHouse.Controllers
{
    using AutoMapper;
    using BuyHouse.Infrastructure;
    using BuyHouse.Models.Issues;
    using BuyHouse.Services.Agents;
    using BuyHouse.Services.Issues;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class IssuesController : Controller
    {
        private readonly IIssueService issueService;
        private readonly IAgentService agentService;
        private readonly IMapper mapper;

        public IssuesController(IIssueService issueService, IAgentService agentService, IMapper mapper) 
        {
            this.issueService = issueService;
            this.agentService = agentService;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Create() 
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]

        public IActionResult Create(CreateIssueFormModel issue, int id) 
        {
            var userId = this.User.GetId();
            var userIsAgent = agentService.IsAgent(userId);
            var userIsAdmin = this.User.IsAdmin();

            var propertyId = id;

            if (userIsAgent || userIsAdmin) 
            {
                return BadRequest();
            }

            if (!ModelState.IsValid) 
            {
                return View(issue);
            }

            this.issueService.Create(
                propertyId,
                userId,
                issue.DescriptionIssue);

            return this.RedirectToAction("All", "Properties");
        }

        [Authorize]
        public IActionResult Edit(int id) 
        {
            var userId = this.User.GetId();
            var userIsAdmin = this.User.IsAdmin();

            var issue = this.issueService.Details(id);

            if (issue.UserId != userId && userIsAdmin)
            {
                return Unauthorized();
            }

            var issueForm = this.mapper.Map<CreateIssueFormModel>(issue);

            return this.View(issueForm);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, CreateIssueFormModel issue)
        {
            var agentId = agentService.AgentsId(this.User.GetId());

            if (agentId == 0)
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }

            if (!ModelState.IsValid) 
            {
                return View(issue);
            }

            this.issueService.Edit(
                id,
                issue.DescriptionIssue,
                issue.CreateOn);

            return this.RedirectToAction("AgentProperties", "Properties");
        }

        [Authorize]
        public IActionResult Delete(int id) 
        {
            var agentId = this.agentService.AgentsId(this.User.GetId());

            if (agentId == 0)
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }

            this.issueService.Delete(id);

            return this.RedirectToAction("AgentProperties", "Properties");
        }

        [Authorize]
        public IActionResult IssueInfo(int id) 
        {
            var issues = this.issueService.AllIssue(id);

            return this.View(issues);
        }
    }
}

BuyHouse/BuyHouse/Controllers/PropertiesController.cs
namespace BuyHouse.Controllers
{
    using AutoMapper;
    using BuyHouse.Infrastructure;
    using BuyHouse.Models.Properties;
    using BuyHouse.Services.Agents;
    using BuyHouse.Services.Properties;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class PropertiesController : Controller
    {
        private readonly IPropertyService propertyService;
        private readonly IAgentService agentService;
        private readonly IMapper mapper;

        public PropertiesController(IPropertyService propertyService, IAgentService agentService, IMapper mapper) 
        {
            this.propertyService = propertyService;
            this.agentService = agentService;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add() 
        {
            if (!this.agentService.IsAgent(this.User.GetId())) 
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }

            return this.View(new PropertyFormModel
            {
                Categories = this.propertyService.AllCategory(),
            }); 
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(PropertyFormModel property) 
        {
            var agentId = this.agentService.AgentsId(this.User.GetId());

            if (agentId == 0) 
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }
            if (!this.propertyService.CategoryExist(property.CategotyId)) 
            {
                this.ModelState.AddModelError(nameof(property.CategotyId), "Category does not exist");
            }

            if (!ModelState.IsValid) 
            {
                property.Categories = this.propertyService.AllCategory();

                return this.View(property);
            }

            var propertyId = this.propertyService.Create(
                property.Area,
                property.Title,
                property.Year,
                property.Floor,
                property.Floors,
                property.BedRoom,
                property.Bath,
                property.Price,
                property.ImageUrl,
                property.Description,
                property.CategotyId,
                property.TypeOfTransaction,
                property.City,
                property.Construction,
                agentId);

            return this.RedirectToAction("Details", "Properties", new { id = propertyId});
        }

        public IActionResult All([FromQuery]AllPropertyModel property) 
        {
            var queryProperties = this.propertyService.All(
                property.Transaction,
                property.City,
                property.Construction,
                property.CurentPage,
                AllPropertyModel.ObjectPerPage);

            var propertiesCity = this.propertyService.AllCity();
            var propertyConstruction = this.propertyService.AllConstruction();
            var propertyTransaction = this.propertyService.AllTransaction();

            property.TotalProperties = queryProperties.TotalProperties;
            property.Cities = propertiesCity;
            property.Constructions = propertyConstruction;
            property.Transactions = propertyTransaction;
            property.Properties = queryProperties.Properties;

            return this.View(property);
        }

        [Authorize]
        public IActionResult Details(int id) 
        {
            var property = this.propertyService
                .Details(id);

            return this.View(property);
        }

        [Authorize]
        public IActionResult Edit(int id) 
        {
            var userId = this.User.GetId();

            if (!this.agentService.IsAgent(userId) && !User.IsAdmin()) 
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }

            var property = this.propertyService.Details(id);

            if (property.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var propertyForm = this.mapper.Map<PropertyFormModel>(property);

            propertyForm.Categories = this.propertyService.AllCategory();

            return View(propertyForm);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, PropertyFormModel property) 
        {
            var agentId = agentService.AgentsId(this.User.GetId());

            if (agentId == 0 && !User.IsAdmin()) 
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }
            if (!this.propertyService.CategoryExist(property.CategotyId)) 
            {
                this.ModelState.AddModelError(nameof(property.CategotyId), "Category does not exist");
            }
            if (!ModelState.IsValid) 
            {
                property.Categories = this.propertyService.AllCategory();

                return this.View(property);
            }
            if (!this.propertyService.AgentIsCreate(id, (int)agentId) && !User.IsAdmin()) 
            {
                return BadRequest();
            }

            this.propertyService.Edit(
                id,
                property.Area,
                property.Title,
                property.Year,
                property.Floor,
                property.Floors,
                property.BedRoom,
                property.Bath,
                property.Price,
                property.ImageUrl,
                property.Description,
                property.CategotyId,
                property.TypeOfTransaction,
                property.City,
                property.Construction,
                this.User.IsAdmin());

            return this.RedirectToAction("Details", "Properties", new { id = id});
        }

        [Authorize]
        public IActionResult Delete(int id) 
        {
            var agentId = this.agentService.AgentsId(this.User.GetId());

            if (agentId == 0 && !User.IsAdmin()) 
            {
                return RedirectToAction(nameof(AgentsController.Create), "Agents");
            }

            this.propertyService.Delete(id);

            return this.RedirectToAction("All", "Properties");
        }

        [Authorize]
        public IActionResult AgentProperties() 
        {
            var properties = this.propertyService.AgentProperties(this.User.GetId());

            return this.View(properties);
        }

        [Authorize]
        public IActionResult CurentAgent(int id) 
        {
            var properties = this.propertyService.CurentAgentProperties(id);

            return this.View(properties);
        }
    }
}

BuyHouse/BuyHouse/Views/Properties/Add.cshtml
@model PropertyFormModel

@{
    ViewData["Title"] = "Add Property";
}

<partial name="_PropertyFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BuyHouse/BuyHouse/Views/Properties/AgentProperties.cshtml
@model IEnumerable<PropertyServiceListModel>

@{
    ViewData["Title"] = "My Proprties";
    ViewBag.AllowPropertyEdit = true;
}

@if (!Model.Any())
{
    <h2 class="text-center">You dont have property</h2>
}

<partial name="_PropertyPartial" model="@Model" />

<hr />

BuyHouse/BuyHouse/Views/Properties/All.cshtml
@model AllPropertyModel

@{
    ViewData["Title"] = $"All Properties, Page {Model.CurentPage} ";

}

@if (!Model.Properties.Any())
{
    <h2 class="text-center">No property found</h2>
}

<form method="get">
    <div class="row mb-5">
        <div class="form-group col-md-3">
            <label asp-for="Transaction"></label>
            <select asp-for="Transaction" class="form-control">
                <option value="">All</option>

                @foreach (var transaction in Model.Transactions)
                {
                    <option value="@transaction">@transaction</option>
                }
            </select>
        </div>
        <div class="form-group col-md-3">
            <label asp-for="City"></label>
            <select asp-for="City" class="form-control">
                <option value="">All</option>

                @foreach (var city in Model.Cities)
                {
                    <option value="@city">@city</option>
                }
            </select>
        </div>
        <div class="form-group col-md-3">
            <label asp-for="Construction"></label>
            <select asp-for="Construction" class="form-control">
                <option value="">All</option>

                @foreach (var construction in Model.Constructions)
                {
                    <option value="@construction">@construction</option>
                }
            </select>
        </div>
        <div>
            <input type="submit" class="btn btn-primary offset-10 mt-4" value="Serch">
        </div>
    </div>
</form>

<partial name="_PropertyPartial" model="@Model.Properties" />
<hr />

@{
    var previousPage = Model.CurentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = (int)Math.Ceiling((double)Model.TotalProperties / AllPropertyModel.ObjectPerPage);

}
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="btn btn-info @(Model.CurentPage == 1 ? "disabled" : string.Empty)"
               asp-controller="Properties"
               asp-action="All"
               asp-route-curentPage="@previousPage"
               asp-route-city="@Model.City"
               asp-route-transaction="@Model.Transaction"
               asp-route-construction="@Model.Construction">Previous</a>
        </li>
        <li class="page-item active">
            <a class="page-link">@Model.CurentPage<span class="sr-only">(current)</span></a>
        </li>

        <li class="page-item">
            <a class="btn btn-info @(Model.CurentPage == maxPage ? "disabled" : string.Empty)"
               asp-controller="Properties"
               asp-action="All"
               asp-route-curentPage="@(Model.CurentPage + 1)"
               asp-route-city="@Model.City"
               asp-route-transaction="@Model.Transaction"
               asp-route-construction="@Model.Construction">Next</a>
        </li>
    </ul>
</nav>

BuyHouse/BuyHouse/Views/Properties/CurentAgent.cshtml
@model IEnumerable<PropertyServiceListModel>

@{
    ViewData["Title"] = "Agent Proprties";
}

@if (!Model.Any())
{
    <h2 class="text-center">Agent dont have property</h2>
}

<partial name="_PropertyPartial" model="@Model" />

<hr />

BuyHouse/BuyHouse/Views/Properties/Details.cshtml
@model PropertyDetailsServiceModel

@inject IAgentService Agent

@{
    ViewData["Title"] = "Detail property";
}

@{
    var userId = User.GetId();
    var userIsAgent = Agent.IsAgent(userId);
    var userIsAdmin = User.IsAdmin();
}
<div class="col-md-4">
    <div class="card mb-3 " style="width: 18rem">
        <h2 class="heading-margin text-center">Property Details</h2>
        <img class="card-img-top" src="@Model.ImageUrl" alt="@Model.Title  - @Model.Year (@Model.City)">
        <div class="card-body">
            <h5 class="card-title text-center">@Model.TypeOfTransaction - @Model.Title</h5>
            <h4 class="card-title text-left">Price : @Model.Price EUR</h4>
            <p class="card-title text-left">City - @Model.City ; Year - @Model.Year</p>
            <p class="card-title text-left">Area - @Model.Area sq m</p>
            @if (Model.Floor.HasValue)
            {
                <p class="card-title text-left">Floor  @Model.Floor from @Model.Floors </p>
            }
            @if (Model.BedRoom.HasValue)
            {
                <p class="card-title text-left">BedRoom - @Model.BedRoom</p>
            }
            @if (Model.Bath.HasValue)
            {
                <p class="card-title text-left">Bath - @Model.Bath</p>
            }
            <p class="card-title text-left">Construction - @Model.Construction</p>
            <h6 class="card-text text-left">Category - @Model.CategoryName</h6>
            <hr />
            <p class="card-title text-left">Description - @Model.Description</p>
            <a asp-controller="Properties" asp-action="All" class="btn btn-primary">Back</a>
            @if (this.User.Identity.IsAuthenticated && !userIsAgent && !userIsAdmin)
            {
                <a class="btn btn-success" asp-area="" asp-controller="Issues" asp-action="Create" asp-route-id="@Model.Id">Create Issue</a>
            }
        </div>
    </div>
</div>

BuyHouse/BuyHouse/Views/Properties/Edit.cshtml
@model PropertyFormModel

@{
    ViewData["Title"] = "Edit Property";
}

<partial name="_PropertyFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BuyHouse/BuyHouse/Views/Properties/_PropertyFormPartial.cshtml
@model PropertyFormModel

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6  col-lg-8">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Area"></label>
                    <input asp-for="Area" class="form-control" placeholder="enter area size">
                    <span asp-validation-for="Area" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="enter title">
                    <span asp-validation-for="Title" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Year"></label>
                    <input asp-for="Year" class="form-control" placeholder="enter year">
                    <span asp-validation-for="Year" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Floor"></label>
                    <input asp-for="Floor" class="form-control" placeholder="enter floor number">
                </div>
                <div class="form-group">
                    <label asp-for="Floors"></label>
                    <input asp-for="Floors" class="form-control" placeholder="enter floors number">
                </div>
                <div class="form-group">
                    <label asp-for="BedRoom"></label>
                    <input asp-for="BedRoom" class="form-control" placeholder="enter number of bedroom">
                </div>
                <div class="form-group">
                    <label asp-for="Bath"></label>
                    <input asp-for="Bath" class="form-control" placeholder="enter number of bath">
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control" placeholder="enter area size">
                    <span asp-validation-for="Price" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl"></label>
                    <input asp-for="ImageUrl" class="form-control" placeholder="enter imageUrl">
                    <span asp-validation-for="ImageUrl" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control" rows="4" placeholder="some description"></textarea>
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Construction"></label>
                    <input asp-for="Construction" class="form-control" placeholder="enter type of material">
                    <span asp-validation-for="Construction" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City"></label>
                    <input asp-for="City" class="form-control" placeholder="enter City name">
                    <span asp-validation-for="City" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TypeOfTransaction"></label>
                    <input asp-for="TypeOfTransaction" class="form-control" placeholder="enter type of transaction">
                    <span asp-validation-for="TypeOfTransaction" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategotyId"></label>
                    <select asp-for="CategotyId" class="form-control">
                        @foreach (var category in Model.Categories)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="CategotyId" class="small text-danger"></span>
                </div>
                <input class="btn btn-primary" type="submit" value="Save" />
            </form>
        </div>
    </div>
</div>

BuyHouse/BuyHouse/Views/Properties/_PropertyPartial.cshtml
@model IEnumerable<PropertyServiceListModel>

<div class="row">
    @foreach (var property in Model)
    {
        <div class="card mb-3 mr-5" style="width: 18rem;">
            <img class="card-img-top" src="@property.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@property.Title</h5>
                <p class="card-text">@property.City</p>
                @if (ViewBag.AllowPropertyEdit == true)
                {
                    <a asp-controller="Issues" asp-action="IssueInfo" asp-route-id="@property.Id" class="btn btn-primary">Issues</a>
                    <a asp-controller="Properties" asp-action="Edit" asp-route-id="@property.Id" class="btn btn-warning">Edit</a>
                    <a asp-controller="Properties" asp-action="Delete" asp-route-id="@property.Id" class="btn btn-danger">Delete</a>
                }
                else if (User.IsAdmin())
                {
                    <a asp-controller="Properties" asp-action="Details" asp-route-id="@property.Id" class="btn btn-primary">Details</a>
                    <a asp-controller="Properties" asp-action="Edit" asp-route-id="@property.Id" class="btn btn-warning">Edit</a>
                    <a asp-controller="Properties" asp-action="Delete" asp-route-id="@property.Id" class="btn btn-danger">Delete</a>
                }
                else
                {
                    <a asp-controller="Properties" asp-action="Details" asp-route-id="@property.Id" class="btn btn-primary">Details</a>
                }
            </div>
        </div>
    }
</div>