BuyHouse/BuyHouse/Areas/Admin/Models/Users/AllUserModel.cs
namespace BuyHouse.Areas.Admin.Models.Users
{
    using BuyHouse.Areas.Admin.Services.Users;
    using System.Collections.Generic;

    public class AllUserModel
    {
        public int CurentPage { get; set; } = 1;

        public int UserPerPage { get; set; } = 5;

        public int TotalUsers { get; set; }

        public IEnumerable<UserServiceListModel> Users { get; set; }
    }
}

BuyHouse/BuyHouse/Areas/Admin/Controllers/UsersController.cs
namespace BuyHouse.Areas.Admin.Controllers
{
    using BuyHouse.Areas.Admin.Models.Users;
    using BuyHouse.Areas.Admin.Services.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static AdminConstants;

    [Area(AreaName)]
    [Authorize(Roles = AdministratolRoleName)]
    public class UsersController : Controller
    {
        private readonly IUserService service;

        public UsersController(IUserService service) 
        {
            this.service = service;
        }

        public IActionResult All([FromQuery] AllUserModel user) 
        {

            var queryUser = this.service.All(
                user.UserPerPage,
                user.CurentPage);

            user.TotalUsers = queryUser.TotalUsers;
            user.Users = queryUser.Users;

            return this.View(user);
        }
    }
}

BuyHouse/BuyHouse/Controllers/AgentsController.cs
namespace BuyHouse.Controllers
{
    using BuyHouse.Infrastructure;
    using BuyHouse.Models.Agents;
    using BuyHouse.Services.Agents;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class AgentsController : Controller
    {
        private readonly IAgentService agentService;

        public AgentsController(IAgentService agentService) 
        {
            this.agentService = agentService;
        }

        [Authorize]
        public IActionResult Create() 
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(AgentFormModel agent) 
        {
            var userId = this.User.GetId();
            var userIsAgent = agentService.IsAgent(userId);

            if (userIsAgent) 
            {
                return BadRequest();
            }

            if (!ModelState.IsValid) 
            {
                return View(agent);
            }

            this.agentService.Create(
               agent.Name,
               agent.PhoneNumber,
               agent.Description,
               agent.ImageUrl,
               agent.City,
               userId);

            return this.RedirectToAction("All", "Properties"); 
        }

        [Authorize]
        public IActionResult All([FromQuery]AllAgentModel agent) 
        {
            var agentQuery = this.agentService.All(
                agent.CurentPage,
                AllAgentModel.ObjectPerPage);

            agent.TotalAgents = agentQuery.TotalAgents;
            agent.Agents = agentQuery.Agents;

            return this.View(agent);
        }

        [Authorize]
        public IActionResult Details(int id) 
        {
            var agent = this.agentService
                .Details(id);

            if (agent == null) 
            {
                return this.NotFound();
            }

            return this.View(agent);
        }
    }
}

BuyHouse/BuyHouse/Areas/Admin/Views/Users/All.cshtml
@model AllUserModel

@inject IAgentService Agent
@inject IPropertyService Property 

@{
    ViewData["Title"] = $"All User, Page {Model.CurentPage}";
    var index = 1;

}

<h2 class="text-center">All Users</h2>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Number</th>
            <th scope="col">Name</th>
            <th scope="col">Full Name</th>
            <th scope="col">User is Agent</th>
            <th scope="col"></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <th scope="row">@(index)</th>
                <td>@user.UserName</td>
                <td>@user.FullName</td>
                <td>@(user.IsAgent ? "Yes" : "No")</td>
                <td>
                    @if (user.IsAgent)
                    {
                        @if (!Property.AgentProperties(user.Id).Any())
                        {
                            <a asp-area="Admin" asp-controller="Agents" asp-action="Delete" asp-route-id="@Agent.AgentsId(user.Id)" class="btn btn-danger float-right ml-3">Delete</a>
                        }
                        <a asp-area="Admin" asp-controller="Agents" asp-action="Edit" asp-route-id="@Agent.AgentsId(user.Id)" class="btn btn-warning float-right ml-3">Edit</a>
                        <a asp-area="" asp-controller="Agents" asp-action="Details" asp-route-id="@Agent.AgentsId(user.Id)" class="btn btn-primary float-right ml-3">Details</a>
                    }
                </td>
            </tr>
            index += 1;
        }
    </tbody>
</table>
<hr />

@{
    var previousPage = Model.CurentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = (int)Math.Ceiling((double)Model.TotalUsers / Model.UserPerPage);

}

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="btn btn-info @(Model.CurentPage == 1 ? "disabled" : string.Empty)"
               asp-controller="Users"
               asp-action="All"
               asp-route-curentPage="@previousPage">Previous</a>
        </li>
        <li class="page-item active">
            <a class="page-link">@Model.CurentPage<span class="sr-only">(current)</span></a>
        </li>

        <li class="page-item">
            <a class="btn btn-info @(Model.CurentPage == maxPage ? "disabled" : string.Empty)"
               asp-controller="Users"
               asp-action="All"
               asp-route-curentPage="@(Model.CurentPage + 1)">Next</a>
        </li>
    </ul>
</nav>